[package]
name = "byteserde_derive"
version = "0.2.0"
edition = "2021"
license-file = "../LICENSE"
description = "A procedural macro for serializing and deserializing structs to and from bytes with focus on performance"
repository = "https://github.com/softstream-link/byteserde"
readme = "../readme.md"
keywords = ["serde", "bytes", "serialization", "deserialization", "procedural-macro"]
categories = ["finance" ]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["extra-traits", "full"] }
quote = "1.0"

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }

