# samples https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
name: Push to master
on:
  push:
    branches:
      - main

jobs:
  push-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Toolchain Info
        run: |
          cargo --version --verbose
          rustc --version
      - name: Test
        run: |
          cargo test
          cargo test --examples
      - name: Benchmark
        run: cargo bench
      - name: Clippy Deny Warnings
        run: cargo clippy --all-features -- --deny warnings
      - name: Publish Dry Run to crates.io
        run: |
          pwd
          ls -la
          pushd byteserde
          cargo publish --dry-run
          popd
          pushd byteserde_derive
          cargo publish --dry-run
          popd
          pushd byteserde_types
          cargo publish --dry-run
          popd
    



