# samples https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
name: Feature Branch Build On Stable
on:
  push:
     branches:
      - '*'
      - '!master'
jobs:
  test-stable-ubuntu:
    uses: ./.github/workflows/workflow-test.yml
    with: 
      toolchain: stable
      chosen-os: ubuntu-latest

  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: dtolnay/rust-toolchain@stable
  #       with:
  #         components: clippy
  # test:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: taiki-e/install-action@nextest
  #     - name: Test
  #       run: |
  #         cargo nextest run --all-features
  #         cargo nextest run --examples --all-features
  #         cargo test --doc --all-features
  #         cargo doc --all-features
  # clippy:
  #   needs: setup    
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Clippy
  #       run: cargo clippy --all-features -- --deny warnings
  # bench:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Benchmark
  #       run: cargo bench
