# samples https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
name: Feature Branch Build On Nightly
on:
  push:
     branches:
      - '*'
      - '!master'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: taiki-e/install-action@nextest
      - name: Toolchain Info
        run: |
          cargo --version --verbose
          rustc --version
      - name: Test
        run: |
          cargo nextest run # --success-output final
          cargo nextest run --examples # --success-output final
          cargo test --doc #  NOTE: docs are not supported by nextest
          cargo doc --all-features # TODO how to fail on warnings?
      - name: Benchmark
        run: cargo bench
      - name: Clippy Deny Warnings
        run: cargo clippy --all-features -- --deny warnings
      - name: Publish Dry Run to crates.io
        run: |
          pwd
          ls -la
          pushd byteserde
          cargo publish --dry-run
          popd
          pushd byteserde_derive
          cargo publish --dry-run
          popd


    
    



