# samples https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
name: Test Snapshot
on:
  pull_request:
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Toolchain Info
        run: |
          cargo --version --verbose
          rustc --version
      - name: Test
        run: |
          cargo test
          cargo test --examples
      - name: Benchmark
        run: cargo bench
      - name: Clippy Deny Warnings
        run: cargo clippy --all-features -- --deny warnings
      - name: Publish Dry Run to crates.io
        run: |
          pushd byteserde
          cargo publish --dry-run
          popd
          pushd byteserde_derive
          cargo publish --dry-run
          popd


    
    



